version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: vibe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vibe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vibe-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      # DATABASE_URL is taken from .env; fallback to local postgres container
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/vibe?schema=public}
      # Allow overriding Redis too, default to internal service
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      PORT: ${PORT:-3000}
    ports:
      - "1337:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vibe-network
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    command: npm run start:dev
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
    ports:
      - "10000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vibe-network
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # command: npm run start:dev

volumes:
  postgres_data:
  redis_data:

networks:
  vibe-network:
    driver: bridge 
